#!/usr/bin/env bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
SCRIPT_NAME=$( basename "$0" )
PYVENV="${PYVENV:-$HOME/.pyvenv}"
VENV="$PYVENV/$SCRIPT_NAME"

#
# Do any setup needed
#
deactivate 2> /dev/null
source "$VENV/bin/activate"

# Path to software entry point
SOFTWARE="$SCRIPT_DIR/$SCRIPT_NAME.py"

# Add any default args here
SOFTWARE_ARGS=$@

# Run software, passing all args from this script onwards
python3 $SOFTWARE $SOFTWARE_ARGS
